#!/bin/bash

# Handle parameters
IMAGE="$1"
DESCRIPTION="$2"
MENDER_AUTH_USERNAME="$3"
MENDER_AUTH_PASSWORD="$4"
if [ ! -n "${IMAGE}" ] || [ ! -n "${DESCRIPTION}" ]
then
    (>&2 echo)
    (>&2 echo "Usage:")
    (>&2 echo "    mender-deployments-post <image> <description> [username] [password]")
    (>&2 echo)
    exit 1
fi

# Ensure curl is installed
curl --help 2>&1 >/dev/null
if [ $? -ne 0 ]
then
    (>&2 echo "Error: Curl is not installed.")
    exit 1
fi

# Ensure python is installed
python --help 2>&1 >/dev/null
if [ $? -ne 0 ]
then
    (>&2 echo "Error: Python is not installed.")
    exit 1
fi

# Ensure build environment is initialized
bitbake --help 2>&1 >/dev/null
if [ "$?" -ne 0 ]
then
    (>&2 echo "Error: Build environment not initialized.")
    exit 1
fi

# Retrieve Mender parameters
MENDER_DEVICE_TYPE=$(bitbake -e | grep -P '^MENDER_DEVICE_TYPE=".+"$' | awk '{split($0,a,"="); print a[2]}' | sed -e 's/^"//' -e 's/"$//')
if [ ! -n "${MENDER_DEVICE_TYPE}" ]
then
    (>&2 echo "Error: Mender device type not found.")
    exit 1
fi
MENDER_SERVER_URL=$(bitbake -e | grep -P '^MENDER_SERVER_URL=".+"$' | awk '{split($0,a,"="); print a[2]}' | sed -e 's/^"//' -e 's/"$//')
if [ ! -n "${MENDER_SERVER_URL}" ]
then
    (>&2 echo "Error: Mender server URL not found.")
    exit 1
fi

# Locate Mender artifact
if [ -d "${BUILDDIR}/tmp" ]
then
    BUILDTMP="${BUILDDIR}/tmp"
else
    BUILDTMP="${BUILDDIR}/tmp-glibc"
fi
MENDER_ARTIFACT="${BUILDTMP}/deploy/images/${MENDER_DEVICE_TYPE}/${IMAGE}-${MENDER_DEVICE_TYPE}.mender"
if [ ! -f "${MENDER_ARTIFACT}" ]
then
    (>&2 echo "Error: Mender artifact not found (${MENDER_ARTIFACT}).")
    exit 1
fi
MENDER_ARTIFACT_REAL="$(readlink -f ${MENDER_ARTIFACT})"
if [ ! -f "${MENDER_ARTIFACT_REAL}" ]
then
    (>&2 echo "Error: Read Mender artifact not found (${MENDER_ARTIFACT_REAL}).")
    exit 1
fi
MENDER_ARTIFACT_SIZE=$(stat --printf="%s" "${MENDER_ARTIFACT_REAL}")

# Show script banner
echo
echo "mender-deployments-post"
echo "By John Lawrence M. Penafiel (penafieljlm)"
echo
echo "Image: ${IMAGE}"
echo "Description: ${DESCRIPTION}"
echo
echo "Device: ${MENDER_DEVICE_TYPE}"
echo "Server: ${MENDER_SERVER_URL}"
echo
echo "Artifact: "
echo "${MENDER_ARTIFACT_REAL}"
echo

# Perform Mender authentication
if [ ! -n "$MENDER_AUTH_USERNAME" ] || [ ! -n "$MENDER_AUTH_PASSWORD" ]
then
    echo "Please enter your Mender credentials."
    echo
    if [ ! -n "$MENDER_AUTH_USERNAME" ]
    then
        read -p "Username: " MENDER_AUTH_USERNAME
    fi
    if [ ! -n "$MENDER_AUTH_PASSWORD" ]
    then
        read -sp "Password: " MENDER_AUTH_PASSWORD
    fi
    echo
fi
echo
MENDER_AUTH_URL="${MENDER_SERVER_URL}/api/management/v1/useradm/auth/login"
MENDER_AUTH_RESULT=$(curl -X POST -u "${MENDER_AUTH_USERNAME}:${MENDER_AUTH_PASSWORD}" "${MENDER_AUTH_URL}" 2>/dev/null)
MENDER_AUTH_ERROR=$(echo "${MENDER_AUTH_RESULT}" | python -c 'import sys, json; print json.load(sys.stdin)["error"];' 2>/dev/null)
if [ -n "${MENDER_AUTH_ERROR}" ]
then
    (>&2 echo "Error: $(tr '[:lower:]' '[:upper:]' <<< ${MENDER_AUTH_ERROR:0:1})${MENDER_AUTH_ERROR:1}.")
    exit 1
fi
MENDER_AUTH_TOKEN="${MENDER_AUTH_RESULT}"

# Upload the Mender artifact
echo "Uploading artifact: ${MENDER_ARTIFACT_REAL}..."
echo
MENDER_ARTIFACTS_URL="${MENDER_SERVER_URL}/api/management/v1/deployments/artifacts"
MENDER_ARTIFACTS_RESULT=$(curl -X POST \
    -H "Authorization: Bearer ${MENDER_AUTH_TOKEN}" \
    -F "description=${DESCRIPTION}" \
    -F "size=${MENDER_ARTIFACT_SIZE}" \
    -F "artifact=@${MENDER_ARTIFACT_REAL}" \
    "${MENDER_ARTIFACTS_URL}")
MENDER_ARTIFACTS_ERROR=$(echo "${MENDER_ARTIFACTS_RESULT}" | python -c 'import sys, json; print json.load(sys.stdin)["error"];' 2>/dev/null)
if [ -n "${MENDER_ARTIFACTS_ERROR}" ]
then
    (>&2 echo "Error: $(tr '[:lower:]' '[:upper:]' <<< ${MENDER_ARTIFACTS_ERROR:0:1})${MENDER_ARTIFACTS_ERROR:1}.")
    exit 1
fi

echo
